### ISSUE TITLE
detailed table guidelines

### ISSUE THREAD

**Issue by sballesteros** [scienceai/docx-standard-scientific-style#70]
thead tfoot, what are the default, how to change them

**Comment by tiffbogich** [comment]
# Tables

## Examples
- th (table heading)
- tf (table footer)
- lc (left column)
- rc (right column)
- mh-cont (multiple headings contiguous)
- mh-dis (multiple headings not contiguous)
- mb (multi-body)

### Cochrane Reviews
#### [Interventions for improving upper limb function after stroke](http://onlinelibrary.wiley.com/doi/10.1002/14651858.CD010820.pub2/epdf)
- Table 1,2: lc, th
- Table 18-20, 22 (p 146): th, variable lc **weird**
- Figure 4 (p23) looks like it should be a table.  based on the shading it looks like multiple 'left columns' for each heading at the top. 


#### [Pharmacological interventions for smoking cessation: an overview and network meta-analysis](http://onlinelibrary.wiley.com/enhanced/doi/10.1002/14651858.CD009329.pub2)
- Table 1: th, mh-dis
- Tables 2, 3: lc, th, tf
- Table 4: th, mh-cont, lc, tf (looks like footnotes rather than tf in the 'total' sense)


#### [Interventions to improve safe and effective medicines use by consumers: an overview of systematic reviews](http://onlinelibrary.wiley.com/enhanced/doi/10.1002/14651858.CD007768.pub3)
- Table 1: one column, mh-disc
- Table 2: mh-cont and mh-disc

#### [Pharmacological interventions for self-harm in adults](http://onlinelibrary.wiley.com/enhanced/doi/10.1002/14651858.CD011777)
- Table 1: mh-cont, lc, tf (as table footnotes)
- Summary of findings tables: column headings extend non uniformly down rows

### Econometrics

#### [Non-Parametric Estimation of Intraday Spot Volatility: Disentangling Instantaneous Trend and Seasonality](http://www.mdpi.com/2225-1146/3/4/864/htm)
- Table 1: th, mh-disc, lc (multiple)

#### [Forecasting Interest Rates Using Geostatistical Techniques](http://www.mdpi.com/2225-1146/3/4/733)
- Table 1: mh-disc, lc (multiple and uneven)
- Table 2: multiple table footers
- Table 3: mh-disc and mh-cont, lc (multiple)

#### [Counterfactual Distributions in Bivariate Models—A Conditional Quantile Approach](http://www.mdpi.com/2225-1146/3/4/719)
- Table 1: mh-disc, tf, lc (multi levels)
- Table 2: mh-disc, lc (multi levels)
